#plugins:
#  - jekyll-remote-theme

#remote_theme: zivhub/monophase@main
remote_theme: pages-themes/primer
#remote_theme: eecs485staff/primer-spec
#remote_theme: riggraz/no-style-please

name: Curso de Introducción a la Astronomía (Calvià; 11 Feb. 2023)
title: null
# see: https://github.com/pages-themes/primer/issues/21

#title: Curso de Astronomía 2022 en Palma de Mallorca
#description: A short description of your site's purpose
#name: Ernesto Nicola

#github:
#  private: true
